version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-diamante
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
